#!/bin/bash
function my_ip(){
        public=$(curl -s ipinfo.io/ip)
        private=$(ifconfig $interface | grep broadcast | awk "{print $2}" | cut -c 14-28)
        router=$(ip route | grep default | cut -c 13-26)
        logo1=$(figlet -f slant -c "fsociety" | lolcat -f)
        logo2=$(figlet -f digital -c "Fuck The Society" | lolcat -f)
        echo "${logo1}"
        echo "${logo2}"
        echo "                                                                                                           "
        echo "  "                                                                                                         "                                                                                             "
        echo -e "              \e[0;31m         Public Ip:\e[0;32m ${public}                                                                "
        echo ""
        echo  -e "             \e[0;31m         Private Ip: \e[0;32m${private}                                                             "
        echo ""
        echo -e "             \e[0;31m          Router Ip:\e[0;32m ${router}                                                               "
}
PS3="Enter choice : "

select interface in wlan0 eth0 exit
do
   if [ $REPLY -eq 1 ];then
        my_ip
        exit 0
    elif [ $REPLY -eq 2 ];then
        my_ip
        exit 0
    elif [ $REPLY -eq 3 ];then
         exit 0
    else 
        echo "Invalid Option"
    fi
done
